# Tabla de Contenidos

* [Contenidos](#Tabla-de-Contenidos)
    * [Listas](#Listas)
    * [Lista vacía](#Lista-vacía)
    * [Agregar elemento(s) a una lista](#Agregar-elemento(s)-a-una-lista)
    * [Operaciones con listas](#Operaciones-con-listas)
* [Ejercicios](#Ejercicios)

## Listas

Este tipo de dato permite agrupar datos (incluso de diferentes tipos) relacionados entre sí.

### Lista vacía

Una lista vacía se crea asignando un par de corchetes sin contenido, como se muestra a continuación.

<br><br>
<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/python_listas0.png?raw=true" width="60%">
</div>

In [4]:
# Cree dos listas vacías: productos y valores  

productos = []
valores = []

<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
productos = []
valores = []
  </code></pre>
</details> 

In [5]:
# Muestre las listas productos y valores  

print(f"Lista productos: {productos}")
print(f"Lista valores: {valores}")

Lista productos: []
Lista valores: []


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
print(f"Lista productos: {productos}")
print(f"Lista valores: {valores}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Agregar elemento(s) a una lista

Para agregar elemento(s) a una lista es posible asignar elementos a la lista **o** utilizar el método `append`.

<br><br>
<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/python_listas1.png?raw=true" width="80%">
</div>

**NOTA:** Con el método `append` se agrega un elemento a la vez. 

In [6]:
# Asigne a la lista productos los elementos: 
#   [ 'CAFE NESCAFE 100 G', 'ARROZ CONEJO SACO 20 LB', 'AZUCAR SAN CARLOS 2 KG', "PAN MOLDE TA'RIKO 450 G", "CHOCOLATE P/TAZA TUNGURAHUA 250 G", "LENTEJON SABOREANDO 500 G"]
# Muestre la lista productos.

productos = [ 'CAFE NESCAFE 100 G', 'ARROZ CONEJO SACO 20 LB', 'AZUCAR SAN CARLOS 2 KG', "PAN MOLDE TA'RIKO 450 G", "CHOCOLATE P/TAZA TUNGURAHUA 250 G", "LENTEJON SABOREANDO 500 G"]

print(f"La lista de productos: {productos}")

La lista de productos: ['CAFE NESCAFE 100 G', 'ARROZ CONEJO SACO 20 LB', 'AZUCAR SAN CARLOS 2 KG', "PAN MOLDE TA'RIKO 450 G", 'CHOCOLATE P/TAZA TUNGURAHUA 250 G', 'LENTEJON SABOREANDO 500 G']


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
productos = [ 'CAFE NESCAFE 100 G', 'ARROZ CONEJO SACO 20 LB', 'AZUCAR SAN CARLOS 2 KG', "PAN MOLDE TA'RIKO 450 G", "CHOCOLATE P/TAZA TUNGURAHUA 250 G", "LENTEJON SABOREANDO 500 G"]
print(f"La lista de productos: {productos}")
  </code></pre>
</details> 

In [7]:
# Para la lista valores, utilice el método append para agregar UNO A UNO de los siguientes datos: 
#   5.29, 11.99, 2.19, 0.99, 2.09 y 1.49
# Muestre la lista valores

valores.append(5.29)
valores.append(11.99)
valores.append(2.19)
valores.append(0.99)
valores.append(2.09)
valores.append(1.49)

print(f"La lista de valores: {valores}")

La lista de valores: [5.29, 11.99, 2.19, 0.99, 2.09, 1.49]


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
valores.append(5.29)
valores.append(11.99)
valores.append(2.19)
valores.append(0.99)
valores.append(2.09)
valores.append(1.49)

print(f"La lista de valores: {valores}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

### Operaciones con listas

Con las listas es posible realizar operaciones como: `max` (valor míximo), `min` (valor máximo), `len` (longitud o cantidad de elementos) y `sum` (suma de todos los elementos). Sin embargo, no todas las operaciones pueden realizarse sobre las listas.


<br><br>
<div align="center">
    <img src="https://github.com/MCD-ESPOL/PCD/blob/main/notebooks/images/python_listas2.png?raw=true" width="60%">
</div>

In [8]:
# En la variable cantidadProductos asigne la cantidad de elementos (len) de la lista productos.
# Muestre el contenido de la variable cantidadProductos

cantidadProductos = len(productos)
print(f"La cantidad de productos es {cantidadProductos}")

La cantidad de productos es 6


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
cantidadProductos = len(productos)
print(f"La cantidad de productos es {cantidadProductos}")
  </code></pre>
</details> 

In [9]:
# En la variable maxValor asigne el valor máximo (max) de la lista valores.
# Muestre el contenido de la variable maxValor


maxValor = max(valores)
print(f"El valor máximo es: {maxValor}")

El valor máximo es: 11.99


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
maxValor = max(valores)
print(f"El valor máximo es: {maxValor}")
  </code></pre>
</details> 

In [10]:
# En la variable minValor asigne el valor mínimo (min) de la lista valores.
# Muestre el contenido de la variable minValor

minValor = min(valores)
print(f"El valor mínimo es: {minValor}")

El valor mínimo es: 0.99


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
minValor = min(valores)
print(f"El valor mínimo es: {minValor}")
  </code></pre>
</details> 

In [11]:
# En la variable totalValor asigne el total (sum) de la lista valores.
# Muestre el contenido de la variable totalValor

totalValor = sum(valores)
print(f"El total es: {totalValor}")

El total es: 24.04


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
totalValor = sum(valores)
print(f"El total es: {totalValor}")
  </code></pre>
</details> 

In [12]:
# En la variable maxProducto asigne el valor máximo (max) de la lista productos.
# Muestre el contenido de la variable maxProducto

maxProducto = max(productos)
print(f"El producto máximo (?): {maxProducto}")

El producto máximo (?): PAN MOLDE TA'RIKO 450 G


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
maxProducto = max(productos)
print(f"El producto máximo (?): {maxProducto}")
  </code></pre>
</details> 

In [13]:
# En la variable minProducto asigne el valor mínimo (min) de la lista productos.
# Muestre el contenido de la variable minProducto

minProducto = min(productos)
print(f"El producto mínimo (?): {minProducto}")

El producto mínimo (?): ARROZ CONEJO SACO 20 LB


<details>
  <summary><div>→ Haga click aquí para ver la solución</div></summary>
  <pre lang="python"><code>
minProducto = min(productos)
print(f"El producto mínimo (?): {minProducto}")
  </code></pre>
</details> 

[Regresar a la TC](#Tabla-de-Contenidos)

## Ejercicios

**Ejercicio 01: Análisis de ventas**

**Temas:** Variables, Tipos de datos, Salida por pantalla, Listas

Crea un programa que utilice con las listas _meses_ y _ventas_.

In [14]:
meses = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
ventas = [3.73, 9.46, 6.01, 5.74, 4.51, 7.6, 6.04, 2.59, 6.88, 7.96, 4.75, 7.96]

1. Mostrar el valor máximo y el valor mínimo de ventas.

2. Mostrar por pantalla total de ventas

3. Calcular y mostrar promedio de ventas.

4. Mostrar el valor máximo de ventas.

5. Mostrar el valor mínimo de ventas.

**Ejercicio 02: Registro de Temperaturas Semanales**

**Temas:** Lista vacía, Agregar elementos a una lista, Operaciones con listas

Escribe un programa que permita al usuario registrar las temperaturas diarias de una semana (7 días). Comienza creando una lista vacía y pide al usuario que ingrese la temperatura para cada día, agregando cada valor a la lista. Al final, el programa debe:

- Mostrar todas las temperaturas ingresadas.
- Calcular y mostrar la temperatura promedio de la semana.
- Mostrar la temperatura más alta y la más baja registrada.

[Regresar a la TC](#Tabla-de-Contenidos)